### ISSUE TITLE
Problem in SDK 34

### ISSUE THREAD

**Issue by RobbyGit** [lorenzofelletti/SimpleBleScanner#2]
Hi There

I had to remove in SDK34 for this to work. Im not sure why just yet
 
MainActivity.kt

Manifest.permission.BLUETOOTH_ADMIN

Thanks

Robby

**Comment by lorenzofelletti** [comment]
Hi Robby! Yes it could be, I developed on SDK 32 or 33, I don't remember exactly. Anyway, I will try to investigate a bit when I have some time.
Thank you for opening the issue!

**Comment by josephsr** [comment]
Hi, 
This is my Manifest file but it still says some permissions missing. Also, the location services permission is enabled for the app
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

Any thoughts?

Thanks,
Joseph

**Comment by josephsr** [comment]
> Hi There
> 
> I had to remove in SDK34 for this to work. Im not sure why just yet
> 
> MainActivity.kt
> 
> Manifest.permission.BLUETOOTH_ADMIN
> 
> Thanks
> 
> Robby

Tried this but still get the toast saying some permissions not granted

**Comment by RobbyGit** [comment]
Ok This is in my Mainfest


    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />



and this is in my MainActivity 

    companion object {
        private const val TAG = "SAPP"
        private const val BLE_PERMISSION_REQUEST_CODE = 1
        private val blePermissions = arrayOf(
            Manifest.permission.BLUETOOTH_SCAN,
            Manifest.permission.ACCESS_COARSE_LOCATION,
            Manifest.permission.ACCESS_FINE_LOCATION,
        )
    }

An it now works..

**Comment by lorenzofelletti** [comment]
I will close the issue, as it seems that you were able to solve it. Feel free to reopen it if needed!
